version: "3.8"
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:6.0
    command: ["mongod", "--port", "8081"]
    ports:
      - "8081:8081"
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata:
